language: php
dist: trusty

jobs:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly

matrix:
    allow_failures:
        - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer install --no-interaction --prefer-dist

install:
  - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script:
- vendor/bin/phpunit